### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Aryan-tripathi-2004** [Aryan-tripathi-2004/Mini_Project_2023#3]
We just started a mini-project which have been given to us by college and in the hurry of completion of project, we are forget about to add favicon on our website.
so can you help us to solve this issue..??
The image which is used in favicon is 
![flower](https://github.com/Aryan-tripathi-2004/Mini_Project_2023/assets/128315876/0766b765-23f6-4512-b3f7-6b5ba64284da)

**Comment by Badr-21** [comment]
I think I can help you, please assign it to me.
